### ISSUE TITLE
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

### ISSUE THREAD

**Issue by Samadfilali** [starpig1129/DATAGEN#11]
hello,
I have this error with the process_agent.
The file OnlineSalesData.csv exists. It seems there is an issue accessing the data_assistant environment on Windows.

What do you think?

================================== Ai Message ==================================
Name: process_agent

{'next': 'Coder', 'task': 'Preprocess the OnlineSalesData.csv dataset, handle missing values and outliers, and prepare the data for machine learning analysis.'}
2024-12-16 07:00:00,803 - logger - INFO - Reading document: ./data_storage/OnlineSalesData.csv
2024-12-16 07:00:00,805 - logger - INFO - Document read successfully: ./data_storage/OnlineSalesData.csv
2024-12-16 07:00:38,445 - logger - INFO - Code will be written to file: data_storage\data_preprocessing.py
2024-12-16 07:00:38,446 - logger - INFO - Code has been written to file: data_storage\data_preprocessing.py
2024-12-16 07:00:38,446 - logger - INFO - Executing command: source /home/user/anaconda3/etc/profile.d/conda.sh && conda activate data_assistant && python data_preprocessing.py
2024-12-16 07:00:38,447 - logger - ERROR - An error occurred while executing code
Traceback (most recent call last):
  File "D:\ai-data-analysis-MulitAgent\tools\basetool.py", line 65, in execute_code
    result = subprocess.run(
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
2024-12-16 07:00:40,838 - logger - INFO - Listing contents of directory: ./data_storage/
2024-12-16 07:00:48,520 - logger - INFO - Code will be written to file: data_storage\data_preprocessing.py
2024-12-16 07:02:21,976 - logger - INFO - Code has been written to file: data_storage\data_preprocessing.py
2024-12-16 07:02:21,983 - logger - INFO - Executing command: source /home/user/anaconda3/etc/profile.d/conda.sh && conda activate data_assistant && python data_preprocessing.py
2024-12-16 07:02:21,983 - logger - ERROR - An error occurred while executing code
Traceback (most recent call last):
  File "D:\ai-data-analysis-MulitAgent\tools\basetool.py", line 65, in execute_code
    result = subprocess.run(
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
2024-12-16 07:02:30,680 - logger - INFO - Code will be written to file: data_storage\code.py
2024-12-16 07:02:30,680 - logger - INFO - Code has been written to file: data_storage\code.py
2024-12-16 07:02:30,681 - logger - INFO - Executing command: source /home/user/anaconda3/etc/profile.d/conda.sh && conda activate data_assistant && python code.py
2024-12-16 07:02:30,682 - logger - ERROR - An error occurred while executing code
Traceback (most recent call last):
  File "D:\ai-data-analysis-MulitAgent\tools\basetool.py", line 65, in execute_code
    result = subprocess.run(
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
================================== Ai Message ==================================
Name: process_agent

{'next': 'Coder', 'task': 'Preprocess the OnlineSalesData.csv dataset, handle missing values and outliers, and prepare the data for machine learning analysis.'}
2024-12-16 07:00:00,803 - logger - INFO - Reading document: ./data_storage/OnlineSalesData.csv
2024-12-16 07:00:00,805 - logger - INFO - Document read successfully: ./data_storage/OnlineSalesData.csv
2024-12-16 07:00:38,445 - logger - INFO - Code will be written to file: data_storage\data_preprocessing.py
2024-12-16 07:00:38,446 - logger - INFO - Code has been written to file: data_storage\data_preprocessing.py
2024-12-16 07:00:38,446 - logger - INFO - Executing command: source /home/user/anaconda3/etc/profile.d/conda.sh && conda activate data_assistant && python data_preprocessing.py
2024-12-16 07:00:38,447 - logger - ERROR - An error occurred while executing code
Traceback (most recent call last):
  File "D:\ai-data-analysis-MulitAgent\tools\basetool.py", line 65, in execute_code
    result = subprocess.run(
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\samad\anaconda3\envs\data_assistant\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
2024-12-16 07:00:40,838 - logger - INFO - Listing contents of directory: ./data_storage/

**Comment by starpig1129** [comment]
New version of basic tools has enhanced support for Windows
